%load smart2_all_1.mat
%load numSamples1.mat
%load smart2.mat
clear;clc
run smart2_load.m
load('/home/xzhuang/Data/xzData20180711/mat/numSamples.mat')

predictorNames = {'smart_5_raw',...
    'smart_187_raw',...
    'smart_197_raw',... 
    'smart_1_normalized',... 
    'smart_4_raw',... 
    'smart_7_normalized',...  
    'smart_9_normalized',...  
    'smart_12_raw',...  
    'smart_183_raw',...  
    'smart_184_raw',...  
    'smart_189_raw',...  
    'smart_193_normalized',...  
    'smart_198_raw',...  
    'smart_199_raw',...  
    'smart_3_normalized',...  
    'smart_5_normalized',...  
    'smart_7_raw',...  
    'smart_9_raw',...  
    'smart_183_normalized',...  
    'smart_184_normalized',...  
    'smart_187_normalized',...  
    'smart_188_normalized',...  
    'smart_188_raw',...  
    'smart_189_normalized',...  
    'smart_192_raw',...  
    'smart_193_raw',...  
    'smart_194_raw',...  
    'smart_197_normalized',...  
    'smart_198_normalized'};

%npRadios = [3 3 3 3 3 5 5 5 5 5 8 8 8 8 8 10 10 10 10 10];
npRadios = [3 5 8 10];
start_date = min(smart2_train.date);
result = cell(length(npRadios)*5,5);
k = 1;
for i_numOfMonth = 1:19
    
    test_start = numSamples.numOfSmart2All(i_numOfMonth) + 1;
    test_end   = numSamples.numOfSmart2All(i_numOfMonth+1);
    smart_test = smart2_all(test_start:test_end, :);
    smart_test = scale_data(smart2_test, 1);
    
%     if i_numOfMonth == 1
%         train_start = 1;
%     else
%         train_start = numSamples.numOfSmart2Train(i_numOfMonth-1) + 1;
%     end
    train_start = 1;
    train_end = numSamples.numOfSmart2Train(i_numOfMonth);
    smart_train = smart2_train(train_start:train_end, :);
    smart_train = scale_data(smart_train, 1);
    smart_pos = smart_train(smart_train.class == 1, :);
    smart_neg = smart_train(smart_train.class == 0, :);

    for j = 1:length(npRadios)
        npRadio = npRadios(j);
        ind = randperm(size(smart_neg, 1));
        smart_neg_p = smart_neg(ind(1:size(smart_pos, 1)*npRadio), :);
        smart_train = [smart_neg_p; smart_pos];
        smart_train = sortrows(smart_train, 'date', 'ascend');
        
        model = rf_train(smart_train, 0.01, predictorNames);
        result{k,1} = rf_test(model, smart_test, predictorNames);
        result{k,2} = sum(smart_train.class == 1);
        result{k,3} = sum(smart_train.class == 0);
        result{k,4} = i_numOfMonth;
        result{k,5} = model;
        k = k+1;
        fprintf('numOfMonth = %d, %dth try\n', i_numOfMonth, j);
    end
end
result{1,:}
%result2_6_5 = cell2table(result, 'VariableNames', {'offlineRF_preResultOnSmart2All_eachMonth', 'numOfPosSample', 'numOfNegSample', 'numOfMonth', 'offlineRFModel'});
%result2_6_5A = cell2table(result, 'VariableNames', {'offlineRF_preResultOnSmart2All_eachMonth', 'numOfPosSample', 'numOfNegSample', 'numOfMonth'});
%save result2_6_5.mat result2_6_5 
