function [model_rf] = rf_train(TrainData, MinParentRadio, predictorNames)

inputTable = TrainData;
predictors = inputTable{:, predictorNames};
response = inputTable.class;

% train random forests
template = templateTree(...
    'MaxNumSplits', 1000, ...
    'MinParentSize', size(inputTable, 1)*MinParentRadio, ...
    'MinLeafSize', 5);
model_rf = fitcensemble(...
    predictors, ...
    response, ...
    'Method', 'Bag', ...
    'NumLearningCycles', 30, ...
    'Learners', template, ...
    'ClassNames', [0; 1]);

end
