function [model_dt] = dt_train(TrainData, MaxNumSplits, predictorNames)

inputTable = TrainData;
predictors = inputTable{:, predictorNames};
response = inputTable.class;

% train decision tree
model_dt = fitctree(...
    predictors, ...
    response, ...
    'SplitCriterion', 'gdi', ...
    'MaxNumSplits', MaxNumSplits, ...
    'Surrogate', 'off', ...
    'PredictorSelection', 'curvature', ...
    'Weights', inputTable{:, 'weights'}, ...
    'ClassNames', [0; 1]);

end
